### ISSUE TITLE
Problem with interlace

### ISSUE THREAD

**Issue by Thxny881** [Dheerajmadhukar/karma_v2#24]
![Screenshot_2024-03-07_20_30_50](https://github.com/Dheerajmadhukar/karma_v2/assets/145889227/08f10a62-4548-4fe0-ad6f-a41ec44fcaff)

I'm having problem with interlace, i uninstalled and installed again, but don't resolve

**Comment by detecht-MK** [comment]
![karma-output](https://github.com/Dheerajmadhukar/karma_v2/assets/162750302/cf29528c-e72c-444d-999a-4810f1524abc)

I've been having a similar issue since I first started using Karma_v2 a couple months ago. I'm guessing I probably did something wrong, but I don't know what it is. Any help pin pointing the cause would be greatly appreciated! Thank you!

**Comment by Dheerajmadhukar** [comment]
Yes I am aware of this issue, and it's also already fixed in new version which I will publish very soon. Keep in touch  :)

**Comment by detecht-MK** [comment]
Awesome! Thank you very much.

**Comment by Thxny881** [comment]
> @Thxny881 mate it's because of your shodan credits. It's ZERO

The files where the results are located are blank, is it because I don't have shodan credits either ?

**Comment by Dheerajmadhukar** [comment]
Yes ! Due to no credits the inscopes ips are not available to proceed with interlace.

**Comment by devileyes10** [comment]
> @Thxny881 mate it's because of your shodan credits. It's ZERO

Hello man! Do we need to have both Query Credet and Scan Credit available? Thank you

**Comment by Dheerajmadhukar** [comment]
Yo just need query credits !

**Comment by devileyes10** [comment]
> Yo just need query credits !

thank you mate

**Comment by LowLevelJody** [comment]
i have the same issue and my credit are still 100. i confused on what should i do
